// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtbRequest {
    /// As per Programmatic Auction Definition IAB TL doc/spec
    #[prost(enumeration = "Lifecycle", tag = "1")]
    pub lifecycle: i32,
    /// ID of the extension point request, assigned by the exchange, and unique for the
    /// exchange's subsequent tracking of the responses. The exchange may use
    /// different values for different recipients.
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
    /// Maximum time in milliseconds the exchange allows for mutations to be received including latency to avoid timeout
    #[prost(int32, tag = "3")]
    pub tmax: i32,
    /// Bid request
    #[prost(message, optional, tag = "4")]
    pub bid_request: ::core::option::Option<
        super::super::super::openrtb::v2::BidRequest,
    >,
    /// Bid response
    #[prost(message, optional, tag = "5")]
    pub bid_response: ::core::option::Option<
        super::super::super::openrtb::v2::BidResponse,
    >,
    /// Business entity that created and owns the enclosed BidRequest or BidResponse
    #[prost(message, optional, tag = "6")]
    pub originator: ::core::option::Option<Originator>,
    /// List of intents the server is eligibible to send back
    #[prost(enumeration = "Intent", repeated, tag = "7")]
    pub applicable_intents: ::prost::alloc::vec::Vec<i32>,
    /// Extension fields
    #[prost(message, optional, tag = "99")]
    pub ext: ::core::option::Option<rtb_request::Ext>,
}
/// Nested message and enum types in `RTBRequest`.
pub mod rtb_request {
    /// Extension fields can be modeled explicitly as needed.
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Ext {}
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtbResponse {
    /// ID of the extension point request to which this is a response.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// List of mutations suggesting changes to be applied
    #[prost(message, repeated, tag = "2")]
    pub mutations: ::prost::alloc::vec::Vec<Mutation>,
    /// Metadata about the response
    #[prost(message, optional, tag = "3")]
    pub metadata: ::core::option::Option<Metadata>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Originator {
    #[prost(enumeration = "originator::Type", tag = "1")]
    pub r#type: i32,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
}
/// Nested message and enum types in `Originator`.
pub mod originator {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Type {
        Unspecified = 0,
        Publisher = 1,
        Ssp = 2,
        Exchange = 3,
        Dsp = 4,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unspecified => "TYPE_UNSPECIFIED",
                Self::Publisher => "TYPE_PUBLISHER",
                Self::Ssp => "TYPE_SSP",
                Self::Exchange => "TYPE_EXCHANGE",
                Self::Dsp => "TYPE_DSP",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "TYPE_UNSPECIFIED" => Some(Self::Unspecified),
                "TYPE_PUBLISHER" => Some(Self::Publisher),
                "TYPE_SSP" => Some(Self::Ssp),
                "TYPE_EXCHANGE" => Some(Self::Exchange),
                "TYPE_DSP" => Some(Self::Dsp),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Mutation {
    /// The purpose of the mutation
    #[prost(enumeration = "Intent", tag = "1")]
    pub intent: i32,
    /// Defines the operation to perform (e.g. add, remove, replace) on the target data at the given path
    #[prost(enumeration = "Operation", tag = "2")]
    pub op: i32,
    /// The semantic business domain of where the operation will be applied
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    /// The structure of value depends on the specified intent.
    /// Reserve 100+ for intent-specific payloads
    #[prost(oneof = "mutation::Value", tags = "100, 101, 102, 103, 104")]
    pub value: ::core::option::Option<mutation::Value>,
}
/// Nested message and enum types in `Mutation`.
pub mod mutation {
    /// The structure of value depends on the specified intent.
    /// Reserve 100+ for intent-specific payloads
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        /// List of string Identifiers
        #[prost(message, tag = "100")]
        Ids(super::IDsPayload),
        /// Adjust properties of a specific deal
        #[prost(message, tag = "101")]
        AdjustDeal(super::AdjustDealPayload),
        /// Adjust the bid price
        #[prost(message, tag = "102")]
        AdjustBid(super::AdjustBidPayload),
        /// Metrics or telemetry data
        #[prost(message, tag = "103")]
        Metrics(super::MetricsPayload),
        /// Content data
        #[prost(message, tag = "104")]
        ContentData(super::DataPayload),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Metadata {
    /// Version of the data provider API
    #[prost(string, tag = "1")]
    pub api_version: ::prost::alloc::string::String,
    /// The model version utilized by the container or API to compute the mutation if applicable
    #[prost(string, tag = "2")]
    pub model_version: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IDsPayload {
    /// List of IDs. Context of the ID is determined by the intent
    #[prost(string, repeated, tag = "1")]
    pub id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AdjustDealPayload {
    /// Suggested bid floor for the deal
    #[prost(double, tag = "1")]
    pub bidfloor: f64,
    /// Suggested margin for the deal
    #[prost(message, optional, tag = "2")]
    pub margin: ::core::option::Option<Margin>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Margin {
    /// The adjusted margin value
    #[prost(double, tag = "1")]
    pub value: f64,
    #[prost(enumeration = "margin::CalculationType", tag = "2")]
    pub calculation_type: i32,
}
/// Nested message and enum types in `Margin`.
pub mod margin {
    /// The type of margin adjustment
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum CalculationType {
        /// Absolute margin adjustment
        Cpm = 0,
        /// Relative margin adjustment (percentage)
        Percent = 1,
    }
    impl CalculationType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Cpm => "CPM",
                Self::Percent => "PERCENT",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "CPM" => Some(Self::Cpm),
                "PERCENT" => Some(Self::Percent),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AdjustBidPayload {
    /// The adjusted bid price
    #[prost(double, tag = "1")]
    pub price: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetricsPayload {
    /// List of metrics to add
    #[prost(message, repeated, tag = "1")]
    pub metric: ::prost::alloc::vec::Vec<
        super::super::super::openrtb::v2::bid_request::imp::Metric,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DataPayload {
    /// List of data to add
    #[prost(message, repeated, tag = "1")]
    pub data: ::prost::alloc::vec::Vec<
        super::super::super::openrtb::v2::bid_request::Data,
    >,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Lifecycle {
    /// Placeholder to Define Programmatic Auction Definition Stages
    Unspecified = 0,
    PublisherBidRequest = 1,
    DspBidResponse = 2,
}
impl Lifecycle {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LIFECYCLE_UNSPECIFIED",
            Self::PublisherBidRequest => "LIFECYCLE_PUBLISHER_BID_REQUEST",
            Self::DspBidResponse => "LIFECYCLE_DSP_BID_RESPONSE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LIFECYCLE_UNSPECIFIED" => Some(Self::Unspecified),
            "LIFECYCLE_PUBLISHER_BID_REQUEST" => Some(Self::PublisherBidRequest),
            "LIFECYCLE_DSP_BID_RESPONSE" => Some(Self::DspBidResponse),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Operation {
    Unspecified = 0,
    Add = 1,
    Remove = 2,
    Replace = 3,
}
impl Operation {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OPERATION_UNSPECIFIED",
            Self::Add => "OPERATION_ADD",
            Self::Remove => "OPERATION_REMOVE",
            Self::Replace => "OPERATION_REPLACE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPERATION_UNSPECIFIED" => Some(Self::Unspecified),
            "OPERATION_ADD" => Some(Self::Add),
            "OPERATION_REMOVE" => Some(Self::Remove),
            "OPERATION_REPLACE" => Some(Self::Replace),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Intent {
    Unspecified = 0,
    /// Activate user segments by their external segment IDs
    ActivateSegments = 1,
    /// Activate deals by their external deal IDs
    ActivateDeals = 2,
    /// Suppress deals by their external deal IDs
    SuppressDeals = 3,
    /// Adjust the bid floor of a specific deal
    AdjustDealFloor = 4,
    /// Adjust the deal margin of a specific deal
    AdjustDealMargin = 5,
    /// Adjust the bid price of a specific bid
    BidShade = 6,
    /// Add metrics to an impression
    AddMetrics = 7,
    /// Add extended content IDs
    AddCids = 8,
}
impl Intent {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "INTENT_UNSPECIFIED",
            Self::ActivateSegments => "ACTIVATE_SEGMENTS",
            Self::ActivateDeals => "ACTIVATE_DEALS",
            Self::SuppressDeals => "SUPPRESS_DEALS",
            Self::AdjustDealFloor => "ADJUST_DEAL_FLOOR",
            Self::AdjustDealMargin => "ADJUST_DEAL_MARGIN",
            Self::BidShade => "BID_SHADE",
            Self::AddMetrics => "ADD_METRICS",
            Self::AddCids => "ADD_CIDS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INTENT_UNSPECIFIED" => Some(Self::Unspecified),
            "ACTIVATE_SEGMENTS" => Some(Self::ActivateSegments),
            "ACTIVATE_DEALS" => Some(Self::ActivateDeals),
            "SUPPRESS_DEALS" => Some(Self::SuppressDeals),
            "ADJUST_DEAL_FLOOR" => Some(Self::AdjustDealFloor),
            "ADJUST_DEAL_MARGIN" => Some(Self::AdjustDealMargin),
            "BID_SHADE" => Some(Self::BidShade),
            "ADD_METRICS" => Some(Self::AddMetrics),
            "ADD_CIDS" => Some(Self::AddCids),
            _ => None,
        }
    }
}
