// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtbRequest {
    /// ENUM as per Programmatic Auction Definition IAB TL doc/spec
    #[prost(enumeration = "Lifecycle", required, tag = "1")]
    pub lifecycle: i32,
    /// ID of the extension point request, assigned by the exchange, and unique for the
    /// exchange's subsequent tracking of the responses. The exchange may use
    /// different values for different recipients.
    /// REQUIRED by the RTB specification.
    #[prost(string, required, tag = "2")]
    pub id: ::prost::alloc::string::String,
    /// Maximum time in milliseconds the exchange allows for mutations to be received including latency to avoid timeout
    /// REQUIRED by the RTB specification.
    #[prost(int32, required, tag = "3")]
    pub tmax: i32,
    /// Bid request
    /// REQUIRED by the RTB specification.
    #[prost(message, required, tag = "4")]
    pub bid_request: super::super::super::openrtb::v2_6::BidRequest,
    /// Bid response
    /// OPTIONAL by the RTB specification.
    #[prost(message, optional, tag = "5")]
    pub bid_response: ::core::option::Option<
        super::super::super::openrtb::v2_6::BidResponse,
    >,
    /// Extension fields
    #[prost(message, optional, tag = "6")]
    pub ext: ::core::option::Option<Extensions>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Extensions {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtbResponse {
    /// ID of the extension point request to which this is a response.
    /// REQUIRED by the RTB specification.
    #[prost(string, required, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// List of mutations suggesting changes to be applied
    #[prost(message, repeated, tag = "2")]
    pub mutations: ::prost::alloc::vec::Vec<Mutation>,
    /// Metadata about the response
    #[prost(message, optional, tag = "3")]
    pub metadata: ::core::option::Option<Metadata>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Mutation {
    /// The purpose of the mutation
    #[prost(enumeration = "Intent", required, tag = "1")]
    pub intent: i32,
    /// Defines the operation to perform (e.g. add, remove, replace) on the target data at the given path
    #[prost(enumeration = "Operation", required, tag = "2")]
    pub op: i32,
    /// The semantic business domain of where the operation will be applied
    #[prost(string, required, tag = "3")]
    pub path: ::prost::alloc::string::String,
    /// The structure of value depends on the specified intent.
    /// Reserve 100+ for intent-specific payloads
    #[prost(oneof = "mutation::Value", tags = "100, 101, 102, 103")]
    pub value: ::core::option::Option<mutation::Value>,
}
/// Nested message and enum types in `Mutation`.
pub mod mutation {
    /// The structure of value depends on the specified intent.
    /// Reserve 100+ for intent-specific payloads
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        /// List of string Identifiers
        #[prost(message, tag = "100")]
        Ids(super::IDsPayload),
        /// Adjust properties of a specific deal
        #[prost(message, tag = "101")]
        AdjustDeal(super::AdjustDealPayload),
        /// Adjust the bid price
        #[prost(message, tag = "102")]
        AdjustBid(super::AdjustBidPayload),
        /// Add metrics or telemetry data
        #[prost(message, tag = "103")]
        AddMetrics(super::AddMetricsPayload),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Metadata {
    /// Version of the data provider API
    #[prost(string, optional, tag = "1")]
    pub api_version: ::core::option::Option<::prost::alloc::string::String>,
    /// The model version utilized by the container or API to compute the mutation if applicable
    #[prost(string, optional, tag = "2")]
    pub model_version: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IDsPayload {
    /// List of IDs. Context of the ID is determined by the intent
    #[prost(string, repeated, tag = "1")]
    pub id: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AdjustDealPayload {
    /// Suggested bid floor for the deal
    #[prost(double, optional, tag = "1")]
    pub bidfloor: ::core::option::Option<f64>,
    /// Suggested margin for the deal
    #[prost(message, optional, tag = "2")]
    pub margin: ::core::option::Option<Margin>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Margin {
    /// The adjusted margin value
    #[prost(double, optional, tag = "1")]
    pub value: ::core::option::Option<f64>,
    #[prost(enumeration = "margin::CalculationType", optional, tag = "2")]
    pub calculation_type: ::core::option::Option<i32>,
}
/// Nested message and enum types in `Margin`.
pub mod margin {
    /// The type of margin adjustment
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum CalculationType {
        /// Absolute margin adjustment
        Cpm = 0,
        /// Relative margin adjustment (percentage)
        Percent = 1,
    }
    impl CalculationType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Cpm => "CPM",
                Self::Percent => "PERCENT",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "CPM" => Some(Self::Cpm),
                "PERCENT" => Some(Self::Percent),
                _ => None,
            }
        }
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AdjustBidPayload {
    /// The adjusted bid price
    #[prost(double, optional, tag = "1")]
    pub price: ::core::option::Option<f64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddMetricsPayload {
    /// List of metrics to add
    #[prost(message, repeated, tag = "1")]
    pub metric: ::prost::alloc::vec::Vec<
        super::super::super::openrtb::v2_6::bid_request::imp::Metric,
    >,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Lifecycle {
    /// Placeholder to Define Programmatic Auction Definition Stages
    Unspecified = 0,
}
impl Lifecycle {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LIFECYCLE_UNSPECIFIED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LIFECYCLE_UNSPECIFIED" => Some(Self::Unspecified),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Operation {
    Unspecified = 0,
    Add = 1,
    Remove = 2,
    Replace = 3,
}
impl Operation {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OPERATION_UNSPECIFIED",
            Self::Add => "OPERATION_ADD",
            Self::Remove => "OPERATION_REMOVE",
            Self::Replace => "OPERATION_REPLACE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPERATION_UNSPECIFIED" => Some(Self::Unspecified),
            "OPERATION_ADD" => Some(Self::Add),
            "OPERATION_REMOVE" => Some(Self::Remove),
            "OPERATION_REPLACE" => Some(Self::Replace),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Intent {
    Unspecified = 0,
    /// Activate user segments by their external segment IDs
    ActivateSegments = 1,
    /// Activate deals by their external deal IDs
    ActivateDeals = 2,
    /// Suppress deals by their external deal IDs
    SuppressDeals = 3,
    /// Adjust the bid floor of a specific deal
    AdjustDealFloor = 4,
    /// Adjust the deal margin of a specific deal
    AdjustDealMargin = 5,
    /// Adjust the bid price of a specific bid
    BidShade = 6,
    /// Add metrics to an impression
    AddMetrics = 7,
}
impl Intent {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "INTENT_UNSPECIFIED",
            Self::ActivateSegments => "ACTIVATE_SEGMENTS",
            Self::ActivateDeals => "ACTIVATE_DEALS",
            Self::SuppressDeals => "SUPPRESS_DEALS",
            Self::AdjustDealFloor => "ADJUST_DEAL_FLOOR",
            Self::AdjustDealMargin => "ADJUST_DEAL_MARGIN",
            Self::BidShade => "BID_SHADE",
            Self::AddMetrics => "ADD_METRICS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INTENT_UNSPECIFIED" => Some(Self::Unspecified),
            "ACTIVATE_SEGMENTS" => Some(Self::ActivateSegments),
            "ACTIVATE_DEALS" => Some(Self::ActivateDeals),
            "SUPPRESS_DEALS" => Some(Self::SuppressDeals),
            "ADJUST_DEAL_FLOOR" => Some(Self::AdjustDealFloor),
            "ADJUST_DEAL_MARGIN" => Some(Self::AdjustDealMargin),
            "BID_SHADE" => Some(Self::BidShade),
            "ADD_METRICS" => Some(Self::AddMetrics),
            _ => None,
        }
    }
}
/// Generated server implementations.
pub mod rtb_extension_point_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with RtbExtensionPointServer.
    #[async_trait]
    pub trait RtbExtensionPoint: std::marker::Send + std::marker::Sync + 'static {
        /// GetMutations returns RTBResponse containing mutations to be applied at the predetermined auction lifecycle event
        async fn get_mutations(
            &self,
            request: tonic::Request<super::RtbRequest>,
        ) -> std::result::Result<tonic::Response<super::RtbResponse>, tonic::Status>;
        /// Server streaming response type for the GetMutationStream method.
        type GetMutationStreamStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::RtbResponse, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn get_mutation_stream(
            &self,
            request: tonic::Request<tonic::Streaming<super::RtbRequest>>,
        ) -> std::result::Result<
            tonic::Response<Self::GetMutationStreamStream>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct RtbExtensionPointServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> RtbExtensionPointServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for RtbExtensionPointServer<T>
    where
        T: RtbExtensionPoint,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/com.iabtechlab.bidstream.mutation.v1.RTBExtensionPoint/GetMutations" => {
                    #[allow(non_camel_case_types)]
                    struct GetMutationsSvc<T: RtbExtensionPoint>(pub Arc<T>);
                    impl<
                        T: RtbExtensionPoint,
                    > tonic::server::UnaryService<super::RtbRequest>
                    for GetMutationsSvc<T> {
                        type Response = super::RtbResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RtbRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RtbExtensionPoint>::get_mutations(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetMutationsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/com.iabtechlab.bidstream.mutation.v1.RTBExtensionPoint/GetMutationStream" => {
                    #[allow(non_camel_case_types)]
                    struct GetMutationStreamSvc<T: RtbExtensionPoint>(pub Arc<T>);
                    impl<
                        T: RtbExtensionPoint,
                    > tonic::server::StreamingService<super::RtbRequest>
                    for GetMutationStreamSvc<T> {
                        type Response = super::RtbResponse;
                        type ResponseStream = T::GetMutationStreamStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::RtbRequest>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RtbExtensionPoint>::get_mutation_stream(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetMutationStreamSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for RtbExtensionPointServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "com.iabtechlab.bidstream.mutation.v1.RTBExtensionPoint";
    impl<T> tonic::server::NamedService for RtbExtensionPointServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
