// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: agenticrtbframework.proto

package artf

import (
	openrtb "github.com/iabtechlab/agentic-rtb-framework/pkg/pb/openrtb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lifecycle int32

const (
	// Placeholder to Define Programmatic Auction Definition Stages
	Lifecycle_LIFECYCLE_UNSPECIFIED Lifecycle = 0
)

// Enum value maps for Lifecycle.
var (
	Lifecycle_name = map[int32]string{
		0: "LIFECYCLE_UNSPECIFIED",
	}
	Lifecycle_value = map[string]int32{
		"LIFECYCLE_UNSPECIFIED": 0,
	}
)

func (x Lifecycle) Enum() *Lifecycle {
	p := new(Lifecycle)
	*p = x
	return p
}

func (x Lifecycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lifecycle) Descriptor() protoreflect.EnumDescriptor {
	return file_agenticrtbframework_proto_enumTypes[0].Descriptor()
}

func (Lifecycle) Type() protoreflect.EnumType {
	return &file_agenticrtbframework_proto_enumTypes[0]
}

func (x Lifecycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Lifecycle) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Lifecycle(num)
	return nil
}

// Deprecated: Use Lifecycle.Descriptor instead.
func (Lifecycle) EnumDescriptor() ([]byte, []int) {
	return file_agenticrtbframework_proto_rawDescGZIP(), []int{0}
}

type Operation int32

const (
	Operation_OPERATION_UNSPECIFIED Operation = 0
	Operation_OPERATION_ADD         Operation = 1
	Operation_OPERATION_REMOVE      Operation = 2
	Operation_OPERATION_REPLACE     Operation = 3
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_ADD",
		2: "OPERATION_REMOVE",
		3: "OPERATION_REPLACE",
	}
	Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_ADD":         1,
		"OPERATION_REMOVE":      2,
		"OPERATION_REPLACE":     3,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_agenticrtbframework_proto_enumTypes[1].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_agenticrtbframework_proto_enumTypes[1]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Operation) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Operation(num)
	return nil
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_agenticrtbframework_proto_rawDescGZIP(), []int{1}
}

type Intent int32

const (
	Intent_INTENT_UNSPECIFIED Intent = 0
	// Activate user segments by their external segment IDs
	Intent_ACTIVATE_SEGMENTS Intent = 1
	// Activate deals by their external deal IDs
	Intent_ACTIVATE_DEALS Intent = 2
	// Suppress deals by their external deal IDs
	Intent_SUPPRESS_DEALS Intent = 3
	// Adjust the bid floor of a specific deal
	Intent_ADJUST_DEAL_FLOOR Intent = 4
	// Adjust the deal margin of a specific deal
	Intent_ADJUST_DEAL_MARGIN Intent = 5
	// Adjust the bid price of a specific bid
	Intent_BID_SHADE Intent = 6
	// Add metrics to an impression
	Intent_ADD_METRICS Intent = 7
)

// Enum value maps for Intent.
var (
	Intent_name = map[int32]string{
		0: "INTENT_UNSPECIFIED",
		1: "ACTIVATE_SEGMENTS",
		2: "ACTIVATE_DEALS",
		3: "SUPPRESS_DEALS",
		4: "ADJUST_DEAL_FLOOR",
		5: "ADJUST_DEAL_MARGIN",
		6: "BID_SHADE",
		7: "ADD_METRICS",
	}
	Intent_value = map[string]int32{
		"INTENT_UNSPECIFIED": 0,
		"ACTIVATE_SEGMENTS":  1,
		"ACTIVATE_DEALS":     2,
		"SUPPRESS_DEALS":     3,
		"ADJUST_DEAL_FLOOR":  4,
		"ADJUST_DEAL_MARGIN": 5,
		"BID_SHADE":          6,
		"ADD_METRICS":        7,
	}
)

func (x Intent) Enum() *Intent {
	p := new(Intent)
	*p = x
	return p
}

func (x Intent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Intent) Descriptor() protoreflect.EnumDescriptor {
	return file_agenticrtbframework_proto_enumTypes[2].Descriptor()
}

func (Intent) Type() protoreflect.EnumType {
	return &file_agenticrtbframework_proto_enumTypes[2]
}

func (x Intent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Intent) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Intent(num)
	return nil
}

// Deprecated: Use Intent.Descriptor instead.
func (Intent) EnumDescriptor() ([]byte, []int) {
	return file_agenticrtbframework_proto_rawDescGZIP(), []int{2}
}

// The type of margin adjustment
type Margin_CalculationType int32

const (
	// Absolute margin adjustment
	Margin_CPM Margin_CalculationType = 0
	// Relative margin adjustment (percentage)
	Margin_PERCENT Margin_CalculationType = 1
)

// Enum value maps for Margin_CalculationType.
var (
	Margin_CalculationType_name = map[int32]string{
		0: "CPM",
		1: "PERCENT",
	}
	Margin_CalculationType_value = map[string]int32{
		"CPM":     0,
		"PERCENT": 1,
	}
)

func (x Margin_CalculationType) Enum() *Margin_CalculationType {
	p := new(Margin_CalculationType)
	*p = x
	return p
}

func (x Margin_CalculationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Margin_CalculationType) Descriptor() protoreflect.EnumDescriptor {
	return file_agenticrtbframework_proto_enumTypes[3].Descriptor()
}

func (Margin_CalculationType) Type() protoreflect.EnumType {
	return &file_agenticrtbframework_proto_enumTypes[3]
}

func (x Margin_CalculationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Margin_CalculationType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Margin_CalculationType(num)
	return nil
}

// Deprecated: Use Margin_CalculationType.Descriptor instead.
func (Margin_CalculationType) EnumDescriptor() ([]byte, []int) {
	return file_agenticrtbframework_proto_rawDescGZIP(), []int{7, 0}
}

type RTBRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ENUM as per Programmatic Auction Definition IAB TL doc/spec
	Lifecycle *Lifecycle `protobuf:"varint,1,req,name=lifecycle,enum=com.iabtechlab.bidstream.mutation.v1.Lifecycle" json:"lifecycle,omitempty"`
	// ID of the extension point request, assigned by the exchange, and unique for the
	// exchange's subsequent tracking of the responses. The exchange may use
	// different values for different recipients.
	// REQUIRED by the RTB specification.
	Id *string `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	// Maximum time in milliseconds the exchange allows for mutations to be received including latency to avoid timeout
	// REQUIRED by the RTB specification.
	Tmax *int32 `protobuf:"varint,3,req,name=tmax" json:"tmax,omitempty"`
	// Bid request
	// REQUIRED by the RTB specification.
	BidRequest *openrtb.BidRequest `protobuf:"bytes,4,req,name=bid_request,json=bidRequest" json:"bid_request,omitempty"`
	// Bid response
	// OPTIONAL by the RTB specification.
	BidResponse *openrtb.BidResponse `protobuf:"bytes,5,opt,name=bid_response,json=bidResponse" json:"bid_response,omitempty"`
	// Extension fields
	Ext           *Extensions `protobuf:"bytes,6,opt,name=ext" json:"ext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTBRequest) Reset() {
	*x = RTBRequest{}
	mi := &file_agenticrtbframework_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTBRequest) ProtoMessage() {}

func (x *RTBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agenticrtbframework_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTBRequest.ProtoReflect.Descriptor instead.
func (*RTBRequest) Descriptor() ([]byte, []int) {
	return file_agenticrtbframework_proto_rawDescGZIP(), []int{0}
}

func (x *RTBRequest) GetLifecycle() Lifecycle {
	if x != nil && x.Lifecycle != nil {
		return *x.Lifecycle
	}
	return Lifecycle_LIFECYCLE_UNSPECIFIED
}

func (x *RTBRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *RTBRequest) GetTmax() int32 {
	if x != nil && x.Tmax != nil {
		return *x.Tmax
	}
	return 0
}

func (x *RTBRequest) GetBidRequest() *openrtb.BidRequest {
	if x != nil {
		return x.BidRequest
	}
	return nil
}

func (x *RTBRequest) GetBidResponse() *openrtb.BidResponse {
	if x != nil {
		return x.BidResponse
	}
	return nil
}

func (x *RTBRequest) GetExt() *Extensions {
	if x != nil {
		return x.Ext
	}
	return nil
}

type Extensions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	extensionFields protoimpl.ExtensionFields
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Extensions) Reset() {
	*x = Extensions{}
	mi := &file_agenticrtbframework_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extensions) ProtoMessage() {}

func (x *Extensions) ProtoReflect() protoreflect.Message {
	mi := &file_agenticrtbframework_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extensions.ProtoReflect.Descriptor instead.
func (*Extensions) Descriptor() ([]byte, []int) {
	return file_agenticrtbframework_proto_rawDescGZIP(), []int{1}
}

type RTBResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the extension point request to which this is a response.
	// REQUIRED by the RTB specification.
	Id *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	// List of mutations suggesting changes to be applied
	Mutations []*Mutation `protobuf:"bytes,2,rep,name=mutations" json:"mutations,omitempty"`
	// Metadata about the response
	Metadata      *Metadata `protobuf:"bytes,3,opt,name=metadata" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RTBResponse) Reset() {
	*x = RTBResponse{}
	mi := &file_agenticrtbframework_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RTBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTBResponse) ProtoMessage() {}

func (x *RTBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agenticrtbframework_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTBResponse.ProtoReflect.Descriptor instead.
func (*RTBResponse) Descriptor() ([]byte, []int) {
	return file_agenticrtbframework_proto_rawDescGZIP(), []int{2}
}

func (x *RTBResponse) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *RTBResponse) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

func (x *RTBResponse) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Mutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The purpose of the mutation
	Intent *Intent `protobuf:"varint,1,req,name=intent,enum=com.iabtechlab.bidstream.mutation.v1.Intent" json:"intent,omitempty"`
	// Defines the operation to perform (e.g. add, remove, replace) on the target data at the given path
	Op *Operation `protobuf:"varint,2,req,name=op,enum=com.iabtechlab.bidstream.mutation.v1.Operation" json:"op,omitempty"`
	// The semantic business domain of where the operation will be applied
	Path *string `protobuf:"bytes,3,req,name=path" json:"path,omitempty"`
	// The structure of value depends on the specified intent.
	// Reserve 100+ for intent-specific payloads
	//
	// Types that are valid to be assigned to Value:
	//
	//	*Mutation_Ids
	//	*Mutation_AdjustDeal
	//	*Mutation_AdjustBid
	//	*Mutation_AddMetrics
	Value         isMutation_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	mi := &file_agenticrtbframework_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_agenticrtbframework_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_agenticrtbframework_proto_rawDescGZIP(), []int{3}
}

func (x *Mutation) GetIntent() Intent {
	if x != nil && x.Intent != nil {
		return *x.Intent
	}
	return Intent_INTENT_UNSPECIFIED
}

func (x *Mutation) GetOp() Operation {
	if x != nil && x.Op != nil {
		return *x.Op
	}
	return Operation_OPERATION_UNSPECIFIED
}

func (x *Mutation) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *Mutation) GetValue() isMutation_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Mutation) GetIds() *IDsPayload {
	if x != nil {
		if x, ok := x.Value.(*Mutation_Ids); ok {
			return x.Ids
		}
	}
	return nil
}

func (x *Mutation) GetAdjustDeal() *AdjustDealPayload {
	if x != nil {
		if x, ok := x.Value.(*Mutation_AdjustDeal); ok {
			return x.AdjustDeal
		}
	}
	return nil
}

func (x *Mutation) GetAdjustBid() *AdjustBidPayload {
	if x != nil {
		if x, ok := x.Value.(*Mutation_AdjustBid); ok {
			return x.AdjustBid
		}
	}
	return nil
}

func (x *Mutation) GetAddMetrics() *AddMetricsPayload {
	if x != nil {
		if x, ok := x.Value.(*Mutation_AddMetrics); ok {
			return x.AddMetrics
		}
	}
	return nil
}

type isMutation_Value interface {
	isMutation_Value()
}

type Mutation_Ids struct {
	// List of string Identifiers
	Ids *IDsPayload `protobuf:"bytes,100,opt,name=ids,oneof"`
}

type Mutation_AdjustDeal struct {
	// Adjust properties of a specific deal
	AdjustDeal *AdjustDealPayload `protobuf:"bytes,101,opt,name=adjust_deal,json=adjustDeal,oneof"`
}

type Mutation_AdjustBid struct {
	// Adjust the bid price
	AdjustBid *AdjustBidPayload `protobuf:"bytes,102,opt,name=adjust_bid,json=adjustBid,oneof"`
}

type Mutation_AddMetrics struct {
	// Add metrics or telemetry data
	AddMetrics *AddMetricsPayload `protobuf:"bytes,103,opt,name=add_metrics,json=addMetrics,oneof"`
}

func (*Mutation_Ids) isMutation_Value() {}

func (*Mutation_AdjustDeal) isMutation_Value() {}

func (*Mutation_AdjustBid) isMutation_Value() {}

func (*Mutation_AddMetrics) isMutation_Value() {}

type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version of the data provider API
	ApiVersion *string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion" json:"api_version,omitempty"`
	// The model version utilized by the container or API to compute the mutation if applicable
	ModelVersion  *string `protobuf:"bytes,2,opt,name=model_version,json=modelVersion" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_agenticrtbframework_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_agenticrtbframework_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_agenticrtbframework_proto_rawDescGZIP(), []int{4}
}

func (x *Metadata) GetApiVersion() string {
	if x != nil && x.ApiVersion != nil {
		return *x.ApiVersion
	}
	return ""
}

func (x *Metadata) GetModelVersion() string {
	if x != nil && x.ModelVersion != nil {
		return *x.ModelVersion
	}
	return ""
}

type IDsPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of IDs. Context of the ID is determined by the intent
	Id            []string `protobuf:"bytes,1,rep,name=id" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDsPayload) Reset() {
	*x = IDsPayload{}
	mi := &file_agenticrtbframework_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDsPayload) ProtoMessage() {}

func (x *IDsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agenticrtbframework_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDsPayload.ProtoReflect.Descriptor instead.
func (*IDsPayload) Descriptor() ([]byte, []int) {
	return file_agenticrtbframework_proto_rawDescGZIP(), []int{5}
}

func (x *IDsPayload) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

type AdjustDealPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Suggested bid floor for the deal
	Bidfloor *float64 `protobuf:"fixed64,1,opt,name=bidfloor" json:"bidfloor,omitempty"`
	// Suggested margin for the deal
	Margin        *Margin `protobuf:"bytes,2,opt,name=margin" json:"margin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustDealPayload) Reset() {
	*x = AdjustDealPayload{}
	mi := &file_agenticrtbframework_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustDealPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustDealPayload) ProtoMessage() {}

func (x *AdjustDealPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agenticrtbframework_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustDealPayload.ProtoReflect.Descriptor instead.
func (*AdjustDealPayload) Descriptor() ([]byte, []int) {
	return file_agenticrtbframework_proto_rawDescGZIP(), []int{6}
}

func (x *AdjustDealPayload) GetBidfloor() float64 {
	if x != nil && x.Bidfloor != nil {
		return *x.Bidfloor
	}
	return 0
}

func (x *AdjustDealPayload) GetMargin() *Margin {
	if x != nil {
		return x.Margin
	}
	return nil
}

type Margin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The adjusted margin value
	Value           *float64                `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
	CalculationType *Margin_CalculationType `protobuf:"varint,2,opt,name=calculation_type,json=calculationType,enum=com.iabtechlab.bidstream.mutation.v1.Margin_CalculationType" json:"calculation_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Margin) Reset() {
	*x = Margin{}
	mi := &file_agenticrtbframework_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Margin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Margin) ProtoMessage() {}

func (x *Margin) ProtoReflect() protoreflect.Message {
	mi := &file_agenticrtbframework_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Margin.ProtoReflect.Descriptor instead.
func (*Margin) Descriptor() ([]byte, []int) {
	return file_agenticrtbframework_proto_rawDescGZIP(), []int{7}
}

func (x *Margin) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *Margin) GetCalculationType() Margin_CalculationType {
	if x != nil && x.CalculationType != nil {
		return *x.CalculationType
	}
	return Margin_CPM
}

type AdjustBidPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The adjusted bid price
	Price         *float64 `protobuf:"fixed64,1,opt,name=price" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustBidPayload) Reset() {
	*x = AdjustBidPayload{}
	mi := &file_agenticrtbframework_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustBidPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustBidPayload) ProtoMessage() {}

func (x *AdjustBidPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agenticrtbframework_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustBidPayload.ProtoReflect.Descriptor instead.
func (*AdjustBidPayload) Descriptor() ([]byte, []int) {
	return file_agenticrtbframework_proto_rawDescGZIP(), []int{8}
}

func (x *AdjustBidPayload) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

type AddMetricsPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of metrics to add
	Metric        []*openrtb.BidRequest_Imp_Metric `protobuf:"bytes,1,rep,name=metric" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMetricsPayload) Reset() {
	*x = AddMetricsPayload{}
	mi := &file_agenticrtbframework_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMetricsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMetricsPayload) ProtoMessage() {}

func (x *AddMetricsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agenticrtbframework_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMetricsPayload.ProtoReflect.Descriptor instead.
func (*AddMetricsPayload) Descriptor() ([]byte, []int) {
	return file_agenticrtbframework_proto_rawDescGZIP(), []int{9}
}

func (x *AddMetricsPayload) GetMetric() []*openrtb.BidRequest_Imp_Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

var File_agenticrtbframework_proto protoreflect.FileDescriptor

const file_agenticrtbframework_proto_rawDesc = "" +
	"\n" +
	"\x19agenticrtbframework.proto\x12$com.iabtechlab.bidstream.mutation.v1\x1a'com/iabtechlab/openrtb/v2/openrtb.proto\"\xd6\x02\n" +
	"\n" +
	"RTBRequest\x12M\n" +
	"\tlifecycle\x18\x01 \x02(\x0e2/.com.iabtechlab.bidstream.mutation.v1.LifecycleR\tlifecycle\x12\x0e\n" +
	"\x02id\x18\x02 \x02(\tR\x02id\x12\x12\n" +
	"\x04tmax\x18\x03 \x02(\x05R\x04tmax\x12F\n" +
	"\vbid_request\x18\x04 \x02(\v2%.com.iabtechlab.openrtb.v2.BidRequestR\n" +
	"bidRequest\x12I\n" +
	"\fbid_response\x18\x05 \x01(\v2&.com.iabtechlab.openrtb.v2.BidResponseR\vbidResponse\x12B\n" +
	"\x03ext\x18\x06 \x01(\v20.com.iabtechlab.bidstream.mutation.v1.ExtensionsR\x03ext\"\x16\n" +
	"\n" +
	"Extensions*\b\bd\x10\x80\x80\x80\x80\x02\"\xb7\x01\n" +
	"\vRTBResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\tR\x02id\x12L\n" +
	"\tmutations\x18\x02 \x03(\v2..com.iabtechlab.bidstream.mutation.v1.MutationR\tmutations\x12J\n" +
	"\bmetadata\x18\x03 \x01(\v2..com.iabtechlab.bidstream.mutation.v1.MetadataR\bmetadata\"\x85\x04\n" +
	"\bMutation\x12D\n" +
	"\x06intent\x18\x01 \x02(\x0e2,.com.iabtechlab.bidstream.mutation.v1.IntentR\x06intent\x12?\n" +
	"\x02op\x18\x02 \x02(\x0e2/.com.iabtechlab.bidstream.mutation.v1.OperationR\x02op\x12\x12\n" +
	"\x04path\x18\x03 \x02(\tR\x04path\x12D\n" +
	"\x03ids\x18d \x01(\v20.com.iabtechlab.bidstream.mutation.v1.IDsPayloadH\x00R\x03ids\x12Z\n" +
	"\vadjust_deal\x18e \x01(\v27.com.iabtechlab.bidstream.mutation.v1.AdjustDealPayloadH\x00R\n" +
	"adjustDeal\x12W\n" +
	"\n" +
	"adjust_bid\x18f \x01(\v26.com.iabtechlab.bidstream.mutation.v1.AdjustBidPayloadH\x00R\tadjustBid\x12Z\n" +
	"\vadd_metrics\x18g \x01(\v27.com.iabtechlab.bidstream.mutation.v1.AddMetricsPayloadH\x00R\n" +
	"addMetricsB\a\n" +
	"\x05value\"P\n" +
	"\bMetadata\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12#\n" +
	"\rmodel_version\x18\x02 \x01(\tR\fmodelVersion\"\x1c\n" +
	"\n" +
	"IDsPayload\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\tR\x02id\"u\n" +
	"\x11AdjustDealPayload\x12\x1a\n" +
	"\bbidfloor\x18\x01 \x01(\x01R\bbidfloor\x12D\n" +
	"\x06margin\x18\x02 \x01(\v2,.com.iabtechlab.bidstream.mutation.v1.MarginR\x06margin\"\xb0\x01\n" +
	"\x06Margin\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12g\n" +
	"\x10calculation_type\x18\x02 \x01(\x0e2<.com.iabtechlab.bidstream.mutation.v1.Margin.CalculationTypeR\x0fcalculationType\"'\n" +
	"\x0fCalculationType\x12\a\n" +
	"\x03CPM\x10\x00\x12\v\n" +
	"\aPERCENT\x10\x01\"(\n" +
	"\x10AdjustBidPayload\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\"]\n" +
	"\x11AddMetricsPayload\x12H\n" +
	"\x06metric\x18\x01 \x03(\v20.com.iabtechlab.openrtb.v2.BidRequest.Imp.MetricR\x06metric*&\n" +
	"\tLifecycle\x12\x19\n" +
	"\x15LIFECYCLE_UNSPECIFIED\x10\x00*f\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rOPERATION_ADD\x10\x01\x12\x14\n" +
	"\x10OPERATION_REMOVE\x10\x02\x12\x15\n" +
	"\x11OPERATION_REPLACE\x10\x03*\xae\x01\n" +
	"\x06Intent\x12\x16\n" +
	"\x12INTENT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACTIVATE_SEGMENTS\x10\x01\x12\x12\n" +
	"\x0eACTIVATE_DEALS\x10\x02\x12\x12\n" +
	"\x0eSUPPRESS_DEALS\x10\x03\x12\x15\n" +
	"\x11ADJUST_DEAL_FLOOR\x10\x04\x12\x16\n" +
	"\x12ADJUST_DEAL_MARGIN\x10\x05\x12\r\n" +
	"\tBID_SHADE\x10\x06\x12\x0f\n" +
	"\vADD_METRICS\x10\a2\x88\x01\n" +
	"\x11RTBExtensionPoint\x12s\n" +
	"\fGetMutations\x120.com.iabtechlab.bidstream.mutation.v1.RTBRequest\x1a1.com.iabtechlab.bidstream.mutation.v1.RTBResponseB9Z7github.com/iabtechlab/agentic-rtb-framework/pkg/pb/artf"

var (
	file_agenticrtbframework_proto_rawDescOnce sync.Once
	file_agenticrtbframework_proto_rawDescData []byte
)

func file_agenticrtbframework_proto_rawDescGZIP() []byte {
	file_agenticrtbframework_proto_rawDescOnce.Do(func() {
		file_agenticrtbframework_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agenticrtbframework_proto_rawDesc), len(file_agenticrtbframework_proto_rawDesc)))
	})
	return file_agenticrtbframework_proto_rawDescData
}

var file_agenticrtbframework_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_agenticrtbframework_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_agenticrtbframework_proto_goTypes = []any{
	(Lifecycle)(0),                        // 0: com.iabtechlab.bidstream.mutation.v1.Lifecycle
	(Operation)(0),                        // 1: com.iabtechlab.bidstream.mutation.v1.Operation
	(Intent)(0),                           // 2: com.iabtechlab.bidstream.mutation.v1.Intent
	(Margin_CalculationType)(0),           // 3: com.iabtechlab.bidstream.mutation.v1.Margin.CalculationType
	(*RTBRequest)(nil),                    // 4: com.iabtechlab.bidstream.mutation.v1.RTBRequest
	(*Extensions)(nil),                    // 5: com.iabtechlab.bidstream.mutation.v1.Extensions
	(*RTBResponse)(nil),                   // 6: com.iabtechlab.bidstream.mutation.v1.RTBResponse
	(*Mutation)(nil),                      // 7: com.iabtechlab.bidstream.mutation.v1.Mutation
	(*Metadata)(nil),                      // 8: com.iabtechlab.bidstream.mutation.v1.Metadata
	(*IDsPayload)(nil),                    // 9: com.iabtechlab.bidstream.mutation.v1.IDsPayload
	(*AdjustDealPayload)(nil),             // 10: com.iabtechlab.bidstream.mutation.v1.AdjustDealPayload
	(*Margin)(nil),                        // 11: com.iabtechlab.bidstream.mutation.v1.Margin
	(*AdjustBidPayload)(nil),              // 12: com.iabtechlab.bidstream.mutation.v1.AdjustBidPayload
	(*AddMetricsPayload)(nil),             // 13: com.iabtechlab.bidstream.mutation.v1.AddMetricsPayload
	(*openrtb.BidRequest)(nil),            // 14: com.iabtechlab.openrtb.v2.BidRequest
	(*openrtb.BidResponse)(nil),           // 15: com.iabtechlab.openrtb.v2.BidResponse
	(*openrtb.BidRequest_Imp_Metric)(nil), // 16: com.iabtechlab.openrtb.v2.BidRequest.Imp.Metric
}
var file_agenticrtbframework_proto_depIdxs = []int32{
	0,  // 0: com.iabtechlab.bidstream.mutation.v1.RTBRequest.lifecycle:type_name -> com.iabtechlab.bidstream.mutation.v1.Lifecycle
	14, // 1: com.iabtechlab.bidstream.mutation.v1.RTBRequest.bid_request:type_name -> com.iabtechlab.openrtb.v2.BidRequest
	15, // 2: com.iabtechlab.bidstream.mutation.v1.RTBRequest.bid_response:type_name -> com.iabtechlab.openrtb.v2.BidResponse
	5,  // 3: com.iabtechlab.bidstream.mutation.v1.RTBRequest.ext:type_name -> com.iabtechlab.bidstream.mutation.v1.Extensions
	7,  // 4: com.iabtechlab.bidstream.mutation.v1.RTBResponse.mutations:type_name -> com.iabtechlab.bidstream.mutation.v1.Mutation
	8,  // 5: com.iabtechlab.bidstream.mutation.v1.RTBResponse.metadata:type_name -> com.iabtechlab.bidstream.mutation.v1.Metadata
	2,  // 6: com.iabtechlab.bidstream.mutation.v1.Mutation.intent:type_name -> com.iabtechlab.bidstream.mutation.v1.Intent
	1,  // 7: com.iabtechlab.bidstream.mutation.v1.Mutation.op:type_name -> com.iabtechlab.bidstream.mutation.v1.Operation
	9,  // 8: com.iabtechlab.bidstream.mutation.v1.Mutation.ids:type_name -> com.iabtechlab.bidstream.mutation.v1.IDsPayload
	10, // 9: com.iabtechlab.bidstream.mutation.v1.Mutation.adjust_deal:type_name -> com.iabtechlab.bidstream.mutation.v1.AdjustDealPayload
	12, // 10: com.iabtechlab.bidstream.mutation.v1.Mutation.adjust_bid:type_name -> com.iabtechlab.bidstream.mutation.v1.AdjustBidPayload
	13, // 11: com.iabtechlab.bidstream.mutation.v1.Mutation.add_metrics:type_name -> com.iabtechlab.bidstream.mutation.v1.AddMetricsPayload
	11, // 12: com.iabtechlab.bidstream.mutation.v1.AdjustDealPayload.margin:type_name -> com.iabtechlab.bidstream.mutation.v1.Margin
	3,  // 13: com.iabtechlab.bidstream.mutation.v1.Margin.calculation_type:type_name -> com.iabtechlab.bidstream.mutation.v1.Margin.CalculationType
	16, // 14: com.iabtechlab.bidstream.mutation.v1.AddMetricsPayload.metric:type_name -> com.iabtechlab.openrtb.v2.BidRequest.Imp.Metric
	4,  // 15: com.iabtechlab.bidstream.mutation.v1.RTBExtensionPoint.GetMutations:input_type -> com.iabtechlab.bidstream.mutation.v1.RTBRequest
	6,  // 16: com.iabtechlab.bidstream.mutation.v1.RTBExtensionPoint.GetMutations:output_type -> com.iabtechlab.bidstream.mutation.v1.RTBResponse
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_agenticrtbframework_proto_init() }
func file_agenticrtbframework_proto_init() {
	if File_agenticrtbframework_proto != nil {
		return
	}
	file_agenticrtbframework_proto_msgTypes[3].OneofWrappers = []any{
		(*Mutation_Ids)(nil),
		(*Mutation_AdjustDeal)(nil),
		(*Mutation_AdjustBid)(nil),
		(*Mutation_AddMetrics)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agenticrtbframework_proto_rawDesc), len(file_agenticrtbframework_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agenticrtbframework_proto_goTypes,
		DependencyIndexes: file_agenticrtbframework_proto_depIdxs,
		EnumInfos:         file_agenticrtbframework_proto_enumTypes,
		MessageInfos:      file_agenticrtbframework_proto_msgTypes,
	}.Build()
	File_agenticrtbframework_proto = out.File
	file_agenticrtbframework_proto_goTypes = nil
	file_agenticrtbframework_proto_depIdxs = nil
}
